version: 3
services:
  travbot:
    restart: always
    build: ./server/
    expose:
      - "8888"
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    links:
      - travbot:travbot
