version: "3"
services:
  app:
    restart: always
    build: ./server/
    ports:
      - "8000:8000"
    links:
      - database:database

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    links:
      - app:app

  database:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - /database/.env
    volumes:
      - database-data:/var/lib/postgresql/data
volumes:
  database-data:
    driver: local